name: pre-commit
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://${{ github.token }}@github.com/${{ github.repository }} .
          cd repo
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Blah " >> README.md
          git add -A
          git commit --message "Updated files from pre-commit"
          git push
