name: pre-commit
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.haed_ref }}
          fetch-depth: '0'
      - run: |
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Blah " >> README.md
          git add -A
          git commit --message "Updated files from pre-commit"
          git push origin HEAD:${{ github.head_ref }}
          
